### ISSUE TITLE
주문 목록 페이지 구현

### ISSUE THREAD

**Issue by jhoon9494** [Wanted-PreOnboarding-Team-8/pre-onboarding-9th-4-8#1]
### 주어진 데이터를 이용하여 주문 목록 페이지를 구현해주세요
- [x] 주문 목록 페이지에는 주문에 대한 모든 정보를 표 형태로 확인할 수 있어야 합니다.
- [x] 주문 목록은 페이지네이션이 구현되어야 합니다(한 페이지에 50건의 주문이 보여야 합니다)
- [x] 데이터 중에서 **오늘의 거래건만** 보여지도록 해주세요 (여기서 오늘은 `2023-03-08`일을 의미합니다.)

### 서버에 들어온 주문을 5초마다 최신화 해주세요
- [x] 서버 API는 구현되어 있지 않지만, 구현되어 있다는 가정 하에 요구사항을 충족해주세요

**Comment by jhoon9494** [comment]
#9 Best practice 선정 이유
- react-query를 사용하여 간편하게 refetch 구현
- FrontEnd, BackEnd 각각의 페이지네이션 처리 방식에 대한 분석과 선정 이유 
- mocking api를 이용하여 백엔드(mock api)에 필요한 데이터만 요청하여 order 페이지 구현

**Comment by tnghgks** [comment]
#9 Best practice 선정 이유
- 왜 이렇게 구현했는 지에 관한 근거를 기술
- Date Picker 컴포넌트를 통한 UX 향상
- 어떤 사용자들이 이용할 지 파악하여 사용자들이 필요한 기능을 추가적으로 구현 (기타 통계 기능)
- 관심사 분리가 매우 잘되어 높은 가독성
- Error Boundary를 통한 에러 처리
- 코드 스플리팅을 통한 페이지의 로딩 속도를 개선

**Comment by raw20** [comment]
#9 Best practice 선정 이유

-  Date Picker를 이용하여 날짜별로 필터링기능 추가
- 역할에 따라 컴포넌트 분리
-  interceptors를 이용해 api 처리 
-  데이터의 수치들을 시각화해서 표현
-  실제 서비스라 가정하고 직접 조사하여 근거제시

**Comment by Noeyso** [comment]
#9 Best practice 선정 이유

- Date Picker와 데이터 수치 표시 등 UX를 신경쓴 점
- 관심사분리 및 적절한 변수명 활용으로 가독성이 높은 점
- 프로젝트 시스템에 대한 구체적인 분석

**Comment by greyHairChooseLife** [comment]
#4 Best practice 선정 이유

- api요청 한 번에 제공 된 mock 데이터 단위가 response된다는 가정이 더 정확하다고 생각했습니다. 웹 서비스의 전체를 보는 관점에서는 지헌님 생각도 훌륭하지만, FE에서도 pagenation, filter, sort, search등이 없지 않고 어디에서 처리하든 장단점이 있습니다. 과제를 통해 살펴보고자 했던 것은 프론트엔드 쪽에서 할 수 있는 것들을 보여보라는 쪽이 맞지 않나 생각했습니다.
- 파라미터를 사용하는 커스텀 훅 추상화가 잘 된 점이 좋았습니다.
