### ISSUE TITLE
필터링, 검색 기능 구현

### ISSUE THREAD

**Issue by jhoon9494** [Wanted-PreOnboarding-Team-8/pre-onboarding-9th-4-8#2]
- [x] 기본 정렬은 ID 기준 오름차순으로 구현해주세요
- [x] 표에서 `주문번호`, `거래일 & 거래시간` 버튼을 누르면 각각 내림차순 정렬이 되도록 해주세요
- [x] 주문 처리 상태에 따라 filtering 기능을 구현해주세요
- [x] 고객이름을 검색할 수 있도록 해주세요

**Comment by jhoon9494** [comment]
#14 Best practice 선정 이유
- useQueryString의 적절한 추상화로 재사용성 높임
- 새로운 api를 생성하여 유저 이름 목록을 받고, 유저 이름을 쿼리 스트링에 반영하여 필터링하였음

**Comment by greyHairChooseLife** [comment]
#14 Best practice 선정 이유

- typescript interface를 십분 활용한 쿼리스트링 커스텀 훅의 추상화가 내부를 들여다보지 않아도 쓸 수 있을 정도로 잘 된 점
- 과제의 모호할 수 있는 부분에 근거 있는 가정을 하고, 그에 걸맞은 답을 제시한 점

**Comment by hyorimcho** [comment]
#13 Best practice 선정 이유

- 이전 best practice에 일관되게 변수명 등을 잘 작성한 것
- 사용자의 입장에서 생각한 듯한 필터링 UI 들과 리셋 버튼
- 유틸 함수들을 잘 분리해 놓은 것

**Comment by bokjunwoo** [comment]
https://github.com/Wanted-PreOnboarding-Team-8/pre-onboarding-9th-4-8/pull/14 Best practice 선정 이유
- useQueryString의 추상화
- 필터링 함수를 분리해 가독성을 높인 점
- 유저 이름을 받아오는 api 생성
